### ISSUE TITLE
Supporting http and https

### ISSUE THREAD

**Issue by honnibal** [justindujardin/pathy#28]
We should consider adding a Pathy class that can support http/https endpoints. It wouldn't be able to do all operations, but we could do some, right?

* `path.open()`: This could be mapped into a call to `smart-open` pretty easily.
* `path.exists()`: try/except to open?
* `path.iterdir()`: Not supported?
* `path.chmod()`: Not supported, but should we no-op or raise?
* `path.is_dir()` and `path.is_file()`: Not sure what to do about this.
* `path.rmdir()`: Not supported?
* `path.mkdir()`: Not supported?
* `path.unlink()`: Not supported, or should we issue a delete request?

**Comment by justindujardin** [comment]
I'm going to close this issue because it's stale and I don't plan on implementing it. PRs to add this functionality are welcomed if someone finds it interesting.
