### ISSUE TITLE
Replace dependency on typer, which is no longer supported/updated

### ISSUE THREAD

**Issue by mborsetti** [justindujardin/pathy#65]
Typer is creating dependency conflict hell, and turns out "It’s not clear if this project will be maintained in a sustainable way in the future or not."  If there's a way to use some other package or built-in functionality it would be welcomed.

https://github.com/tiangolo/typer/issues/313:
> A nontrivial patch is required (#280, #278) since this library depends heavily on click 7.x internals.
> 
> The project is maintained solely by @tiangolo.
> 
> * Via Twitter, they have expressed an intent to spend more time on Typer and FastAPI
> * They have been active recently in https://github.com/tiangolo/fastapi/
> * They made a new release of https://github.com/tiangolo/typer-cli/ last month (but without addressing the click 8.x issue)
> * As far as I know, they have not responded to issues or PRs here in many, many months ([[QUESTION] Is the project still maintained? #300](https://github.com/tiangolo/typer/issues/300))
> 
> It’s not clear if this project will be maintained in a sustainable way in the future or not.

**Comment by tiangolo** [comment]
I just released Typer `0.4.0`, which is compatible with **both** Click 7 and Click 8. :tada: 

Upgrading Typer would handle it.

**Comment by justindujardin** [comment]
@mborsetti can you confirm if you still have problems after the `0.4.0` release of typer? 

Pathy uses a `>=0.3.0,<1.0.0` range for [typer](https://github.com/justindujardin/pathy/blob/97187528b70fdb96e928e1f90a3b06732e126b16/requirements.txt#L2), so hopefully we shouldn't need to update anything. 🤞

**Comment by mborsetti** [comment]
@justindujardin  Thanks!  No problems with Pathy, works like a charm. Really appreciate your meaningful contribution to reducing dependency gridlock!
